version: '3.4'

services:
  znxt.net.core.web.sample:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionString=mongodb+srv://Admin:su9P25NsVE79e20w@cluster0-xorwh.mongodb.net/test?retryWrites=true
      - DataBaseName=ZNxtCore_test
    ports:
      - "3496:80"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro